@echo off
call testsingle C:\devel\AttributeReportJava\src\ContinuousFileReader.java
call testsingle C:\devel\AttributeReportJava\src\EOFException.java
call testsingle C:\devel\AttributeReportJava\src\Extension.java
call testsingle C:\devel\AttributeReportJava\src\ExtensionCast.java
call testsingle C:\devel\AttributeReportJava\src\ExtensionClass.java
call testsingle C:\devel\AttributeReportJava\src\ExtensionCommon.java
call testsingle C:\devel\AttributeReportJava\src\ExtensionEnum.java
call testsingle C:\devel\AttributeReportJava\src\ExtensionHead.java
call testsingle C:\devel\AttributeReportJava\src\ExtensionMethod.java
call testsingle C:\devel\AttributeReportJava\src\ExtensionValue.java
call testsingle C:\devel\AttributeReportJava\src\FileIterator.java
call testsingle C:\devel\AttributeReportJava\src\KeywordToID.java
call testsingle C:\devel\AttributeReportJava\src\AttributeReportJava.java
call testsingle C:\devel\AttributeReportJava\src\Lexer.java
call testsingle C:\devel\AttributeReportJava\src\LEXER_ID.java
call testsingle C:\devel\AttributeReportJava\src\Parser.java
call testsingle C:\devel\AttributeReportJava\src\ParserConsole.java
call testsingle C:\devel\AttributeReportJava\src\ParseSetAnalyser.java
call testsingle C:\devel\AttributeReportJava\src\Report.java
call testsingle C:\devel\AttributeReportJava\src\ReportAbstract.java
call testsingle C:\devel\AttributeReportJava\src\ReportClass.java
call testsingle C:\devel\AttributeReportJava\src\ReportControl.java
call testsingle C:\devel\AttributeReportJava\src\ReportMethod.java
call testsingle C:\devel\AttributeReportJava\src\REPORT_LIST_ID.java
call testsingle C:\devel\AttributeReportJava\src\SYMBOL_ID.java
call testsingle C:\devel\AttributeReportJava\src\SyntaxException.java
call testsingle C:\devel\AttributeReportJava\src\KEYWORD_ID.java
call testsingle C:\devel\AttributeReportJava\src\VALUE_ID.java
