java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\batch\Main.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\core\compiler\CharOperation.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\ClassFile.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\Compiler.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\impl\CompilerOptions.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\lookup\LookupEnvironment.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\lookup\ReferenceBinding.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\problem\ProblemReporter.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\util\HashtableOfObject.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\parser\Parser.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\ASTVisitor.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\parser\diagnose\DiagnoseParser.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\ast\BinaryExpression.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\ast\ExplicitConstructorCall.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\ast\FieldReference.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\ast\QualifiedNameReference.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\lookup\Scope.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\parser\Scanner.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\impl\Constant.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\codegen\CodeStream.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\flow\UnconditionalFlowInfo.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\lookup\BinaryTypeBinding.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\lookup\AnnotationBinding.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\ast\IfStatement.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\util\FloatUtil.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\parser\RecoveredLocalVariable.java >> ecj.log
java -jar \bin\ecj.jar -time:detail -5 \src\ecj\org\eclipse\jdt\internal\compiler\classfmt\ClassFileReader.java >> ecj.log
